### ISSUE TITLE
KDE

### ISSUE THREAD

**Issue by MrOctober77** [jpoet/HauppaugeUSB#3] opened 2018-04-15 16:32 UTC
Does this work on KDE systems? Tried it with KDE Neon and Kubunto but keep getting errors executing "make".

**Comment by jpoet** [comment] 2018-04-15 19:26
This package is not dependent on your window manager.

You mention Kubunto, so I assume you are using ubuntu.  I am guessing the issue is a missing dependency.  If you print the error message then we can probably determine which package is needed.

**Comment by MrOctober77** [comment] 2018-04-16 23:19
I figured out what package I needed and got it installed. Couple issues though. It takes several tries to get the recording started.

Sometimes I get this error:

000:00:10.609535 W [HAPI-cmd] Hapi.cpp:382 (cmdThreadFunc) -  pMsgWaitingRsp=0x117a320 waiting for 3372ms(limit=5000)

000:00:11.742638 W [HAPI-cmd] Hapi.cpp:369 (cmdThreadFunc) - SEVERE: pMsgWaitingRsp=0x117a320 appears stuck after 4505ms

000:00:11.742713 E [HAPI-cmd] Hapi.cpp:379 (cmdThreadFunc) - SEVERE: pMsgWaitingRsp=0x117a320 removed from queue

000:00:12.459222 E [main] Hapi.cpp:3182 (HAPI_Start) - HWAPI_MESSAGE_START fail!!! sem err:3, rspCode:0x01000000

000:00:12.459308 E [main] HauppaugeDev.cpp:582 (StartEncoding) - Encoder start capture failed.

 Or this:

000:00:07.195854 N [main] HauppaugeDev.cpp:395 (init_hdmi) - Invalid Output Params, retrying.
000:00:07.699871 N [main] HauppaugeDev.cpp:395 (init_hdmi) - Invalid Output Params, retrying.
000:00:08.203735 N [main] HauppaugeDev.cpp:395 (init_hdmi) - Invalid Output Params, retrying.
000:00:08.722451 N [main] HauppaugeDev.cpp:127 (set_input_format) - Input width: 1920 height: 1080 interlaced: 0 vFreq: 59.9337 audio SR: 0
000:00:08.722917 E [main] FX2Device.cpp:115 (I2CWriteRead) - I2C: Improper answer: status 07
terminate called after throwing an instance of 'std::runtime_error'
  what():  CS8416: device is not ready

**Comment by jpoet** [comment] 2018-04-17 01:45
What package did you need?  I can add it to the README.

What version of the Colossus2 / HD-PVR2 do you have?  It is possible that Hauppauge will need to tweak the code for it.

**Comment by MrOctober77** [comment] 2018-04-17 02:24
sudo apt-get install libmagickwand-dev

1512 Gaming Edition Plus

**Comment by stevenviola** [comment] 2018-11-19 17:43
@MrOctober77, were you able to figure out how to get recording starting. I keep getting the following error message, no matter how many times I try to start things up:

```
000:00:04.867405 N 29875 [main] HauppaugeDev.cpp:127 (set_input_format) - Input width: 1920 height: 1080 interlaced: 1 vFreq: 60 audio SR: 0
000:00:04.867625 E 29875 [main] FX2Device.cpp:115 (I2CWriteRead) - I2C: Improper answer: status 07
terminate called after throwing an instance of 'std::runtime_error'
  what():  CS8416: device is not ready
```

This is happening for me on model 157310

**Comment by jpoet** [comment] 2019-01-09 00:32
MrOctober77, I believe that Steven has figure out the issue and it should be fixed with today's commit.

**Closed** 2019-01-09 00:33 UTC
